version: '3.1'

services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - whatsapp:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redispw
    ports:
      - 6379:6379

volumes:
  whatsapp:
